CREATE DATABASE FACE_RECOGNITION

CREATE TABLE CHECK_IN(
CNAME VARCHAR(100),
CTIMEIN VARCHAR(100),
CDAY VARCHAR(100)
)

SELECT * FROM CHECK_IN
/*Delete from CHECK_IN */

CREATE TABLE CHECK_OUT(
CNAME VARCHAR(100),
CTIMEOUT VARCHAR(100),
CDAY VARCHAR(100)
)
SELECT * FROM CHECK_OUT